#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define spec '|'


// Adds "Accept cookies" pop-up dialog to your html page if one doesn't exist already.
// html_file_path can be relative, e.g. "./index.html", or full path, e.g. "C:\Users\USER\Desktop\project\index.html"
void add_cookies_popup(char *html_file_path){
    FILE *html_file = fopen(html_file_path, "r");
    if(html_file == NULL){
        printf("File %s does not exist.\n", html_file_path);
        return;
    }
    fseek(html_file, 0L, SEEK_END);
    int len = ftell(html_file);
    fseek(html_file, 0L, SEEK_SET);
    char *str = (char*) calloc(len+1,sizeof(char));
    fread(str, 1, len, html_file);
    if(strstr(str, "cookies-eu-banner") != NULL){
        printf("Accept cookies pop-up already exists.\n");
        free(str);
        return;
    }

    if(strstr(str, "<body") == NULL){
        printf("There is no body tag in html file.\n");
        free(str);
        return;
    }

    char *str2 =
        "\n"
        "\n"
        "\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- Cookie banner start -->\n"
        "\n"
		"<div class=\"cookies-eu-banner hidden\">\n"
		"	By clicking \"OK\", you agree to the storing of \n"
		"	<a href=\"https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRVSp6lnjgy68ENobCFIam16G5G-JJ7oXy6cAsKibCpAzga39tvcWbmw9iSeQZmyabl\">cookies</a> on your device to\n"
		"	enhance site navigation, analyze site usage, and improve marketing.\n"
		"	<button>Accept</button>\n"
		"</div>\n"
		"<script>\n"
		"	(() => {\n"
		"		const getCookie = (name) => {\n"
		"			const value = \" \" + document.cookie;\n"
		"			console.log(\"value\", `==${value}==`);\n"
		"			const parts = value.split(\" \" + name + \"=\");\n"
		"			return parts.length < 2 ? undefined : parts.pop().split(\";\").shift();\n"
		"		};\n"
        "\n"
		"		const setCookie = function (name, value, expiryDays, domain, path, secure) {\n"
		"			const exdate = new Date();\n"
		"			exdate.setHours(\n"
		"			exdate.getHours() +\n"
		"				(typeof expiryDays !== \"number\" ? 365 : expiryDays) * 24\n"
		"			);\n"
		"			document.cookie =\n"
		"			name +\n"
		"			\"=\" +\n"
		"			value +\n"
		"			\";expires=\" +\n"
		"			exdate.toUTCString() +\n"
		"			\";path=\" +\n"
		"			(path || \"/\") +\n"
		"			(domain ? \";domain=\" + domain : \"\") +\n"
		"			(secure ? \";secure\" : \"\");\n"
		"		};\n"
        "\n"
		"		const $cookiesBanner = document.querySelector(\".cookies-eu-banner\");\n"
		"		const $cookiesBannerButton = $cookiesBanner.querySelector(\"button\");\n"
		"		const cookieName = \"cookiesBanner\";\n"
		"		const hasCookie = getCookie(cookieName);\n"
        "\n"
		"		if (!hasCookie) {\n"
		"			$cookiesBanner.classList.remove(\"hidden\");\n"
		"		}\n"
        "\n"
		"		$cookiesBannerButton.addEventListener(\"click\", () => {\n"
		"			setCookie(cookieName, \"closed\");\n"
		"			$cookiesBanner.remove();\n"
		"		});\n"
		"	})();\n"
		"</script>\n"
		"<style>\n"
		"	.cookies-eu-banner {\n"
		"	background: #444;\n"
		"	color: #fff;\n"
		"	padding: 6px;\n"
		"	font-size: 13px;\n"
		"	text-align: center;\n"
		"	position: fixed;\n"
		"	bottom: 0;\n"
		"	width: 100%;\n"
		"	z-index: 10;\n"
		"	}\n"
        "\n"
		"	.cookies-eu-banner button {\n"
		"	text-decoration: none;\n"
		"	background: #222;\n"
		"	color: #fff;\n"
		"	border: 1px solid #000;\n"
		"	cursor: pointer;\n"
		"	padding: 4px 7px;\n"
		"	margin: 2px 0;\n"
		"	font-size: 13px;\n"
		"	font-weight: 700;\n"
		"	transition: background 0.07s, color 0.07s, border-color 0.07s;\n"
		"	}\n"
        "\n"
		"	.cookies-eu-banner button:hover {\n"
		"	background: #fff;\n"
		"	color: #222;\n"
		"	}\n"
        "\n"
		"	.hidden {\n"
		"	display: none;\n"
		"	}\n"
		"</style>\n"
        "\n"
		"<!-- Cookie banner end -->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"\n"
		"\n"
		"\n";

    char *str3 = strstr(str, "<body") + 5;
    for(int i = 0; i < 1000; i++){
        if(*(str3++) == '>') break;
    }
    fclose(html_file);
    html_file = fopen(html_file_path, "w");
    fwrite(str, 1, str3 - str, html_file);
    fwrite(str2, 1, strlen(str2), html_file);
    fwrite(str3, 1, strlen(str3), html_file);
    printf("Accept cookies pop-up added to your html file.");
}

/* Kolkas gryba pjauna
void add_tooltip(char *html_file_path, char *element_id, char *tooltip_text){
    FILE *html_file = fopen(html_file_path, "r");
    if(html_file == NULL){
        printf("File %s does not exist.\n", html_file_path);
        return;
    }
    fseek(html_file, 0L, SEEK_END);
    int len = ftell(html_file);
    fseek(html_file, 0L, SEEK_SET);
    char *str = (char*) calloc(len+1,sizeof(char));
    fread(str, 1, len, html_file);

    if(strstr(str, "<html") == NULL){
        printf("There is no html tag in html file.\n");
        free(str);
        return;
    }



    char *str2 = strstr(str, ".tooltip-wrapper") != NULL ? "" :
        "\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<style>\n"
        ".tooltip-wrapper {\n"
        "-webkit-transform: translateZ(0);\n"
        "-webkit-font-smoothing: antialiased;\n"
        "}\n"
        "\n"
        ".tooltip-wrapper .tooltip {\n"
        "border-radius: 4px;\n"
        "display: block;\n"
        "background: #444;\n"
        "color: #fff;\n"
        "opacity: 0;\n"
        "pointer-events: none;\n"
        "position: absolute;\n"
        "width: 200px;\n"
        "-webkit-transform: translateY(10px);\n"
        "-moz-transform: translateY(10px);\n"
        "-ms-transform: translateY(10px);\n"
        "-o-transform: translateY(10px);\n"
        "transform: translateY(10px);\n"
        "-webkit-transition: all .25s ease-out;\n"
        "-moz-transition: all .25s ease-out;\n"
        "-ms-transition: all .25s ease-out;\n"
        "-o-transition: all .25s ease-out;\n"
        "transition: all .25s ease-out;\n"
        "-webkit-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "-moz-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "-ms-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "-o-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "bottom: 100%;\n"
        "left: 0;\n"
        "right: 0;\n"
        "padding: 20px;\n"
        "margin: auto;\n"
        "margin-bottom: 15px;\n"
        "\n"
        "}\n"
        "\n"
        ".tooltip-wrapper .tooltip:before {\n"
        "	bottom: -20px;\n"
        "	content: " ";\n"
        "	display: block;\n"
        "	height: 20px;\n"
        "	left: 0;\n"
        "	position: absolute;\n"
        "	width: 100%;\n"
        "}\n"
        "\n"
        ".tooltip-wrapper .tooltip:after {\n"
        "	border-left: solid transparent 10px;\n"
        "	border-right: solid transparent 10px;\n"
        "	border-top: solid #444 10px;\n"
        "	bottom: -5px;\n"
        "	content: \" \";\n"
        "	height: 0;\n"
        "	left: 50%;\n"
        "	margin-left: -13px;\n"
        "	position: absolute;\n"
        "	width: 0;\n"
        "}\n"
        ".tooltip-wrapper:hover .tooltip {\n"
        "	opacity: 1;\n"
        "	pointer-events: auto;\n"
        "	-webkit-transform: translateY(0px);\n"
        "  	-moz-transform: translateY(0px);\n"
        "  	-ms-transform: translateY(0px);\n"
        "   	-o-transform: translateY(0px);\n"
        "    transform: translateY(0px)\n;"
        "}\n"
        "\n"
        "</style>\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "\n";

    char *str3 = strstr(str, "<html") + 5;
    for(int i = 0; i < 1000; i++){
        if(*(str3++) == '>') break;
    }
    fclose(html_file);
    html_file = fopen(html_file_path, "w");
    fwrite(str, 1, str3 - str, html_file);
    fwrite(str2, 1, strlen(str2), html_file);
    fwrite(str3, 1, strlen(str3), html_file);
    fclose(html_file);

    html_file = fopen(html_file_path, "r");
    fseek(html_file, 0L, SEEK_END);
    int len_new = ftell(html_file);
    fseek(html_file, 0L, SEEK_SET);
    char *str_new = (char*) calloc(len_new + 1,sizeof(char));
    fread(str_new, 1, len_new, html_file);

    char str1_new[1024] = {0};
    int len1_new = sprintf(str1_new, "id=\"%s\"", element_id);
    if(strstr(str_new, str1_new) == NULL){
        printf("Element with property %s not found.\n", str1_new);
        return;
    }

    char *str_new_0 = strstr(str_new, str1_new);
    char* class_start = NULL;
    for(int i = 0; i < 1000; i++){
        if(*(str_new_0--) == '<') break;
        if(*str_new_0 == 'c' && *(str_new_0+1) == 'l' && *(str_new_0+2) == 'a' && *(str_new_0+3) == 's' && *(str_new_0+4) == 's' && ( *(str_new_0+5) == '=' || *(str_new_0+5) == ' ')){
            class_start = str_new_0;
            printf("c");
        }
        printf("%c%c%c%c%c%c\n", *str_new_0, *(str_new_0+1), *(str_new_0+2), *(str_new_0+3), *(str_new_0+4), *(str_new_0+5));
    }
    printf("\n");
    if(class_start == NULL){
        str_new+=5;
        for(int i = 0; i < 1000; i++){
        if(*(str_new_0+=4) == '>') break;
        if(*str_new_0 == 'c' && *(str_new_0+1) == 'l' && *(str_new_0+2) == 'a' && *(str_new_0+3) == 's' && *(str_new_0+4) == 's' && ( *(str_new_0+5) == '=' || *(str_new_0+5) == ' ')){
            printf("b");
            class_start = str_new_0;
        }
        printf("%c%c%c%c%c%c\n", *str_new_0, *(str_new_0+1), *(str_new_0+2), *(str_new_0+3), *(str_new_0+4), *(str_new_0+5));
    }
    }



    if(class_start == NULL){

    }
    else{
        printf("abc");
        char *first_marker = class_start; // add after current char "tooltip-wrapper " without quotation marks
        for(int i = 0; i < 1000; i++){
            if(*(first_marker++) == '\"') break;
        }
        char *second_marker = first_marker; // add "<span class="tooltip">%s</span>" without quotation marks
        for(int i = 0; i < 1000; i++){
            if(*(second_marker++) == '>') break;
        }
        fclose(html_file);
        html_file = fopen(html_file_path, "w");
        fwrite(str_new, 1, first_marker - str, html_file);
        fwrite("tooltip-wrapper ", 1, 16, html_file);
        fwrite(first_marker, 1, second_marker-first_marker, html_file);
        char str88[1024] = {0};
        int len88 = sprintf(str88, "<span class=\"tooltip\">%s</span>", tooltip_text);
        fwrite(str88, 1, len88, html_file);
        fwrite(second_marker, 1, strlen(second_marker), html_file);
        fclose(html_file);
    }



}
*/

// changes website cursor to minecraft sword
void change_cursor(char *html_file_path){

    FILE *html_file = fopen(html_file_path, "r");
    if(html_file == NULL){
        printf("File %s does not exist.\n", html_file_path);
        return;
    }
    fseek(html_file, 0L, SEEK_END);
    int len = ftell(html_file);
    fseek(html_file, 0L, SEEK_SET);
    char *str = (char*) calloc(len+1,sizeof(char));
    fread(str, 1, len, html_file);
    if(strstr(str, "html *{\n       cursor:") != NULL){
        printf("The cursor is already changed for your website.\n");
        free(str);
        return;
    }

    if(strstr(str, "<html") == NULL){
        printf("There is no html tag in html file.\n");
        free(str);
        return;
    }


    char *str2 =
        "\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<style>\n"
        "   html *{\n"
        "       cursor: url(https://i.ibb.co/5G0Gbf2/minecraft-cursor-defaut.png), auto;\n"
        "   }\n"
        "</style>\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "\n";

    char *str3 = strstr(str, "<html") + 5;
    for(int i = 0; i < 1000; i++){
        if(*(str3++) == '>') break;
    }
    fclose(html_file);
    html_file = fopen(html_file_path, "w");
    fwrite(str, 1, str3 - str, html_file);
    fwrite(str2, 1, strlen(str2), html_file);
    fwrite(str3, 1, strlen(str3), html_file);
    printf("Cursor for you website was changed.\n");
}

void htmlEdit(FILE *file, FILE *db){
    int flength, loopDepth = 0, tempLength;
    int repNum[10];
    char copy[1000], replace[1000], fromDatabase[1000];
    char *tempName = malloc(10);
    char *loop;
    strcpy(tempName, "t0.txt");
    FILE **temps = malloc(10 * sizeof(FILE*));
    temps[0] = fopen(tempName, "w+");
    fseek(file, 0, SEEK_END);
    flength = ftell(file);
    fseek(file, 0, SEEK_SET);
    while(ftell(file) < flength){
        fgets(copy, 1000, file);
        loop = strstr(copy, "(repeat) ");
        if(loop == NULL){
            loop = strstr(copy, "(endrep)\n");
            if(loop == NULL){
                fputs(copy, temps[loopDepth]);
            }
            else{
                tempLength = ftell(temps[loopDepth]);
                for(int i = 0; i < repNum[loopDepth]; ++i){
                    tempLength = ftell(temps[loopDepth]);
                    fseek(temps[loopDepth], 0, SEEK_SET);
                    while(ftell(temps[loopDepth]) < tempLength){
                        fgets(copy, 1000, temps[loopDepth]);
                        fputs(copy, temps[loopDepth - 1]);
                    }
                }
                fclose(temps[loopDepth]);
                sprintf(tempName, "t%d.txt", loopDepth);
                remove(tempName);
                --loopDepth;
            }
        }
        else{
            ++loopDepth;
            repNum[loopDepth] = atoi(loop + 9);
            sprintf(tempName, "t%d.txt", loopDepth);
            temps[loopDepth] = fopen(tempName, "w+");
        }
    }
    //---------------------------------------------------------------------
    fseek(file, 0, SEEK_SET);
    fseek(temps[0], 0, SEEK_END);
    flength = ftell(temps[0]);
    fseek(temps[0], 0, SEEK_SET);
    while(ftell(temps[0]) < flength){
        fgets(copy, 1000, temps[0]);
        while(strchr(copy, spec) != NULL){
            fgets(fromDatabase, 1000, db);
            strcpy(replace, strchr(copy, spec) + 1);
            *strchr(copy, spec) = '\0';
            strcat(copy, fromDatabase);
            strcat(copy, replace);
        }
        fputs(copy, file);
    }
    fclose(temps[0]);
    remove("t0.txt");
}

