#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void add_cookies_popup(char *html_file_path);
void add_tooltip(char *html_file_path, char *element_id, char *tooltip_text);
void change_cursor(char *html_file_path);


int main(){
    add_cookies_popup("../index.html");
    change_cursor("../index.html");
}


// Adds "Accept cookies" pop-up dialog to your html page if one doesn't exist already.
// html_file_path can be relative, e.g. "./index.html", or full path, e.g. "C:\Users\USER\Desktop\project\index.html"
void add_cookies_popup(char *html_file_path){
    FILE *html_file = fopen(html_file_path, "r");
    if(html_file == NULL){
        printf("File %s does not exist.\n", html_file_path);
        return;
    }
    fseek(html_file, 0L, SEEK_END);
    int len = ftell(html_file);
    fseek(html_file, 0L, SEEK_SET);
    char *str = (char*) calloc(len+1,sizeof(char));
    fread(str, 1, len, html_file);
    if(strstr(str, "cookies-eu-banner") != NULL){
        printf("Accept cookies pop-up already exists.\n");
        free(str);
        return;
    }

    if(strstr(str, "<body") == NULL){
        printf("There is no body tag in html file.\n");
        free(str);
        return;
    }

    char *str2 =
        "\n"
        "\n"
        "\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- Cookie banner start -->\n"
        "\n"
		"<div class=\"cookies-eu-banner hidden\">\n"
		"	By clicking \"OK\", you agree to the storing of \n"
		"	<a href=\"https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRVSp6lnjgy68ENobCFIam16G5G-JJ7oXy6cAsKibCpAzga39tvcWbmw9iSeQZmyabl\">cookies</a> on your device to\n"
		"	enhance site navigation, analyze site usage, and improve marketing.\n"
		"	<button>Accept</button>\n"
		"</div>\n"
		"<script>\n"
		"	(() => {\n"
		"		const getCookie = (name) => {\n"
		"			const value = \" \" + document.cookie;\n"
		"			console.log(\"value\", `==${value}==`);\n"
		"			const parts = value.split(\" \" + name + \"=\");\n"
		"			return parts.length < 2 ? undefined : parts.pop().split(\";\").shift();\n"
		"		};\n"
        "\n"
		"		const setCookie = function (name, value, expiryDays, domain, path, secure) {\n"
		"			const exdate = new Date();\n"
		"			exdate.setHours(\n"
		"			exdate.getHours() +\n"
		"				(typeof expiryDays !== \"number\" ? 365 : expiryDays) * 24\n"
		"			);\n"
		"			document.cookie =\n"
		"			name +\n"
		"			\"=\" +\n"
		"			value +\n"
		"			\";expires=\" +\n"
		"			exdate.toUTCString() +\n"
		"			\";path=\" +\n"
		"			(path || \"/\") +\n"
		"			(domain ? \";domain=\" + domain : \"\") +\n"
		"			(secure ? \";secure\" : \"\");\n"
		"		};\n"
        "\n"
		"		const $cookiesBanner = document.querySelector(\".cookies-eu-banner\");\n"
		"		const $cookiesBannerButton = $cookiesBanner.querySelector(\"button\");\n"
		"		const cookieName = \"cookiesBanner\";\n"
		"		const hasCookie = getCookie(cookieName);\n"
        "\n"
		"		if (!hasCookie) {\n"
		"			$cookiesBanner.classList.remove(\"hidden\");\n"
		"		}\n"
        "\n"
		"		$cookiesBannerButton.addEventListener(\"click\", () => {\n"
		"			setCookie(cookieName, \"closed\");\n"
		"			$cookiesBanner.remove();\n"
		"		});\n"
		"	})();\n"
		"</script>\n"
		"<style>\n"
		"	.cookies-eu-banner {\n"
		"	background: #444;\n"
		"	color: #fff;\n"
		"	padding: 6px;\n"
		"	font-size: 13px;\n"
		"	text-align: center;\n"
		"	position: fixed;\n"
		"	bottom: 0;\n"
		"	width: 100%;\n"
		"	z-index: 10;\n"
		"	}\n"
        "\n"
		"	.cookies-eu-banner button {\n"
		"	text-decoration: none;\n"
		"	background: #222;\n"
		"	color: #fff;\n"
		"	border: 1px solid #000;\n"
		"	cursor: pointer;\n"
		"	padding: 4px 7px;\n"
		"	margin: 2px 0;\n"
		"	font-size: 13px;\n"
		"	font-weight: 700;\n"
		"	transition: background 0.07s, color 0.07s, border-color 0.07s;\n"
		"	}\n"
        "\n"
		"	.cookies-eu-banner button:hover {\n"
		"	background: #fff;\n"
		"	color: #222;\n"
		"	}\n"
        "\n"
		"	.hidden {\n"
		"	display: none;\n"
		"	}\n"
		"</style>\n"
        "\n"
		"<!-- Cookie banner end -->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
		"\n"
		"\n"
		"\n";

    char *str3 = strstr(str, "<body") + 5;
    for(int i = 0; i < 1000; i++){
        if(*(str3++) == '>') break;
    }
    fclose(html_file);
    html_file = fopen(html_file_path, "w");
    fwrite(str, 1, str3 - str, html_file);
    fwrite(str2, 1, strlen(str2), html_file);
    fwrite(str3, 1, strlen(str3), html_file);
    printf("Accept cookies pop-up added to your html file.");
}

void add_tooltip(char *html_file_path, char *element_id, char *tooltip_text){
    char *str2 = 
    "\n"
    "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
	"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
	"<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
    "<style>\n"
    ".tooltip-wrapper {\n"
    "-webkit-transform: translateZ(0);\n"
    "-webkit-font-smoothing: antialiased;\n"
    "}\n"
    "\n"
    ".tooltip-wrapper .tooltip {\n"
        "border-radius: 4px;\n"
        "display: block;\n"
        "background: #444;\n"
        "color: #fff;\n"	
        "opacity: 0;\n"
        "pointer-events: none;\n"
        "position: absolute;\n"
        "width: 200px;\n"
        "-webkit-transform: translateY(10px);\n"
        "-moz-transform: translateY(10px);\n"
        "-ms-transform: translateY(10px);\n"
        "-o-transform: translateY(10px);\n"
        "transform: translateY(10px);\n"
        "-webkit-transition: all .25s ease-out;\n"
        "-moz-transition: all .25s ease-out;\n"
        "-ms-transition: all .25s ease-out;\n"
        "-o-transition: all .25s ease-out;\n"
        "transition: all .25s ease-out;\n"
        "-webkit-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "-moz-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "-ms-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "-o-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);\n"
        "bottom: 100%;\n"
        "left: 0;\n"
        "right: 0;\n"
        "padding: 20px;\n"
        "margin: auto;\n"
        "margin-bottom: 15px;\n"
        "\n"	
        "}\n"
        "\n"
        ".tooltip-wrapper .tooltip:before {\n"
        "	bottom: -20px;\n"
        "	content: " ";\n"
        "	display: block;\n"
        "	height: 20px;\n"
        "	left: 0;\n"
        "	position: absolute;\n"
        "	width: 100%;\n"
        "}\n"
        "\n"
        ".tooltip-wrapper .tooltip:after {\n"
        "	border-left: solid transparent 10px;\n"
        "	border-right: solid transparent 10px;\n"
        "	border-top: solid #444 10px;\n"
        "	bottom: -5px;\n"
        "	content: \" \";\n"
        "	height: 0;\n"
        "	left: 50%;\n"
        "	margin-left: -13px;\n"
        "	position: absolute;\n"
        "	width: 0;\n"
        "}\n"
        ".tooltip-wrapper:hover .tooltip {\n"
        "	opacity: 1;\n"
        "	pointer-events: auto;\n"
        "	-webkit-transform: translateY(0px);\n"
        "  	-moz-transform: translateY(0px);\n"
        "  	-ms-transform: translateY(0px);\n"
        "   	-o-transform: translateY(0px);\n"
        "    transform: translateY(0px)\n;"
        "}\n"
        "\n"
        "</style>\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "\n";

}

// changes website cursor to minecraft sword
void change_cursor(char *html_file_path){

    FILE *html_file = fopen(html_file_path, "r");
    if(html_file == NULL){
        printf("File %s does not exist.\n", html_file_path);
        return;
    }
    fseek(html_file, 0L, SEEK_END);
    int len = ftell(html_file);
    fseek(html_file, 0L, SEEK_SET);
    char *str = (char*) calloc(len+1,sizeof(char));
    fread(str, 1, len, html_file);
    if(strstr(str, "html *{\n       cursor:") != NULL){
        printf("The cursor is already changed for your website.\n");
        free(str);
        return;
    }

    if(strstr(str, "<html") == NULL){
        printf("There is no html tag in html file.\n");
        free(str);
        return;
    }


    char *str2 =
        "\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "<style>\n"
        "   html *{\n"
        "       cursor: url(https://i.ibb.co/5G0Gbf2/minecraft-cursor-defaut.png), auto;\n"
        "   }\n"
        "</style>\n"
        "<!-- AUTOGENERATED ----------------------------------------------------------------->\n"
        "\n";

    char *str3 = strstr(str, "<html") + 5;
    for(int i = 0; i < 1000; i++){
        if(*(str3++) == '>') break;
    }
    fclose(html_file);
    html_file = fopen(html_file_path, "w");
    fwrite(str, 1, str3 - str, html_file);
    fwrite(str2, 1, strlen(str2), html_file);
    fwrite(str3, 1, strlen(str3), html_file);
    printf("Cursor for you website was changed.\n");
}

