#ifndef HTML
#define HTML

#define DOCTYPE "<!DOCTYPE html>\n"
#define HTML_START "<html>\n"
#define HTML_END "</html>"
#define HEAD_START "\t<head>\n"
#define HEAD_END "\t</head>\n"
#define HEAD_META_CHARSET "\t\t<meta charset=\"utf-8\">\n"
#define HEAD_META_HTTP "\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
#define HEAD_TITLE_START "\t\t<title>CV of "
#define HEAD_TITLE_END "</title>\n"
#define HEAD_META_NAME_DESC "\t\t<meta name=\"description\" content=\"\">\n"
#define HEAD_META_NAME_VIEW "\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
#define HEAD_META_LINK "\t\t<link rel=\"stylesheet\" href=\"style.css\">\n"

#define BODY "\t<body class=\"website\">\n"
#define BODY_BOX "\t\t<div class=\"box\">\n"
#define BODY_BOX_IMG "\t\t\t<img class=\"picture\" src=\"Assets/pfp.jpg\" alt=\"Assets/pfp.png\">\n"
#define BODY_BOX_H1 "\t\t\t<h1 class=\"name\">"
#define BODY_BOX_DIV "\t\t\t<div class=\"field\">"
#define BODY_DESC "\t\t<div class=\"description\">\n"
#define BODY_DESC_ABT "\t\t\t<h1>About Me</h1>\n"
#define BODY_DESC_DIV "\t\t\t<div class=\"desctxt\">\n"
#define BODY_GRID_CON "\t\t\t<div class=\"gridContainer\">\n"
#define BODY_GRID_ITEM "\t\t\t<div class=\"gridItem\">\n"
#define BODY_BIO "\t\t\t\t<h1>BIO</h1>\n"
#define BODY_BIO_AGE "\t\t\t\t<div class=\"bio\">Age - "
#define BODY_BIO_STATUS "\t\t\t\t<div class=\"bio\">Status - "
#define BODY_BIO_OCC "\t\t\t\t<div class=\"bio\">Occupation - "
#define BODY_WTCM "\t\t\t\t<h1>Ways To Contact Me</h1>\n"
#define BODY_WTCM_LI_START "\t\t\t\t<div class=\"bio\"><a href=\""
#define BODY_WTCM_LI_END "\" target=\"_blank\" rel=\"noopener noreferrer\">LinkedIn</a></div>\n"
#define BODY_WTCM_GIT_START "\t\t\t\t<div class=\"bio\"><a href=\""
#define BODY_WTCM_GIT_END "\" target=\"_blank\" rel=\"noopener noreferrer\">GitHub</a></div>\n"
#define BODY_WTCM_EMAIL "\t\t\t\t<div class=\"bio\">Email - "
#define BODY_WTCM_PHONE "\t\t\t\t<div class=\"bio\">Phone - "
#define BODY_WTCM_ADDRESS "\t\t\t\t<div class=\"bio\">Address - "
#define BODY_SKILL_START "\t\t\t\t<h1>"
#define BODY_SKILL_END " Skill(s)</h1>\n"
#define BODY_SKILL_DESC_START "\t\t\t\t<div class=\"bio\">"
#define BODY_SKILL_DESC_MID " - "
#define BODY_SKILL_DESC_END "/10</div>\n"
#define BODY_EDU "\t\t\t\t<h1>Education</h1>\n"
#define BODY_EDU_DEGR "\t\t\t\t<div class=\"bio\">University/College degrees:</div>\n"
#define BODY_EDU_CERT "\t\t\t\t<div class=\"bio\">Additional courses/Certificates:</div>\n"
#define BODY_END "\t</body>\n"

#define PB_START "\t\t\t\t<p><b>\n\t\t\t\t\t"
#define PB_END "\n\t\t\t\t</b></p>\n"
#define H1_END "</h1>\n"
#define DIV_END "</div>\n"
#define DIV_END_NEWLINE "\t\t</div>\n"
#define DIV_END_NEWLINE3 "\t\t\t</div>\n"


#endif